// program for handling exception 
#include <iostream>
#include <stdexcept>

using namespace std;

int main() {
    int num1, num2;

    cout << "Enter two integers for division: ";
    cin >> num1 >> num2;

    try {
        if (num2 == 0) {
            throw runtime_error("Division by zero is not allowed.");
        } else {
            cout << "Result of division: " << num1 / num2 << endl;
        }
    }
    catch (const runtime_error& e) {
        cerr << "Error: " << e.what() << endl;
    }
    catch (...) {
        cerr << "An unknown error occurred." << endl;
    }

    return 0;
}
